### ISSUE TITLE
create vacancies model

### ISSUE THREAD

**Issue by caldwell619** [burn-notice-y/burn-notice#6]

**Comment by caldwell619** [comment]
- `station`: foreign key to station id
- `district`: foreign key to district id
- `engine` boolean
- `postDate`: Date ( String? )
- `fillDate`: Date ( String? )
- `temporary`: boolean

**Comment by ShawnArnold1** [comment]
Finished vacancies, however relationships are still needed to be tweaked once everything else is worked up

**Comment by ShawnArnold1** [comment]
Finished Vacancy model, will need to be revisited when the rest of models/controllers are built
